orderfood:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: OrderFood
    username: root
    password: 
  alioss:
    endpoint: 
    access-key-id: 
    access-key-secret: 
    bucket-name: 
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: 
    secret: 
    mchid: asd
    mch-serial-no: asd
    private-key-file-path: asd
    api-v3-key: asd
    we-chat-pay-cert-file-path: asd
    notify-url: asd
    refund-notify-url: asd
